### ISSUE TITLE
WKT creates more than just the WKT

### ISSUE THREAD

**Issue by Marcus-Vitruvius** [skeenp/QGIS3-getWKT#6] opened 2020-06-11 08:59 UTC
When pushing the WKT-button 2 problems occur.
Problem 1: everything is a multipolygon, even single polygons
Problem 2: although not visible in the windows, when copying the data, the attribute table data is included in the copy. This can become a problem when you paste it in an other application.

Mac OS 10.14.6
QGIS 3.10 
GetWKT 1.3

**Comment by skeenp** [comment] 2021-01-11 05:47
Sorry for the delay, this one slipped past my radar. 

**Problem 1:** I've not experienced this, the WKT is generated from the QGIS asWKT python function so that information is being obtained from QGIS Core, however I can see how it might come about. If the source dataset is of multi type, the tool may deliver the multi type, even if the actual feature only contains a single feature. I cannot reproduce with any of my data, so if you have some example datasets where this occurs happy to check it out. I could add a setting to always demote/promote/match source but don't know of an eta.

**Problem 2:** To avoid copying the attribute data, you need to select the text from within the 'Get WKT' window and the copy, otherwise you will just be copying the source feature from QGIS Core. Auto select/copy is not supported in the plugin.

**Comment by Marcus-Vitruvius** [comment] 2021-01-12 16:20
Hello.

Thank you for your reply.
Meanwhile I have solved this problem in de database where the data is going to. 
It’s being processed first, so that issue is bypassed.

Kind regards

Wouter

**Comment by skeenp** [comment] 2023-03-04 05:43
#11 should make the copy process a little more streamlined and will be released in the next few days.

**Closed as completed by skeenp** 2023-03-04 05:43 UTC
